<a href="https://colab.research.google.com/github/sh1vam31/Complete_DataScience/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pandas**

## 1 What is Pandas and Why Use It?
Pandas is a powerful Python library for data analysis and manipulation.

Key points:

Provides two main data structures: Series (1D) and DataFrame (2D).
Makes working with tabular data easy and fast.
Ideal for cleaning, transforming, and analyzing datasets.
Works well with other libraries like NumPy, Matplotlib, and Scikit-Learn.

### Import the pandas

In [2]:
import numpy as np
import pandas as pd

## 2 Understanding Series & DataFrame



*   Series: One-dimensional labeled array, like a column in Excel.
*   DataFrame: Two-dimensional table, similar to an Excel sheet or SQL table.

## Creating a Series from Python Lists or Dictionaries

In [9]:
a = [12, 34, 45, 74, 66]
s = pd.Series(a, name = "Marks")
s

d = {"vashu": 99, "shivam": 88,}
s2 = pd.Series(d, name = "marks")
s2

vashu     99
shivam    88
Name: marks, dtype: int64

## Creating a DataFrame

In [10]:
a = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Marks": [90, 85, 78, 92],
    "Subject": ["Math", "Science", "History", "English"]
}

pd.DataFrame(a)

      Name  Marks  Subject
0    Alice     90     Math
1      Bob     85  Science
2  Charlie     78  History
3    David     92  English

## Creating DataFrame from NumPy Arrays

In [15]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

df = pd.DataFrame(a, columns = ["A", "B", "C"])
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9